### ISSUE TITLE
Error when using open file

### ISSUE THREAD

**Issue by jlahowetz2** [Photonsters/PhotonFileValidator#92]
I keep getting this error when I try to browse to open a file:

> Exception in thread "Thread-0" java.lang.NullPointerException
> 	at java.io.File.<init>(File.java:277)
> 	at sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:105)
> 	at sun.awt.X11.GtkFileDialogPeer.run(Native Method)
> 	at sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:174)
> 	at sun.awt.X11.GtkFileDialogPeer.access$000(GtkFileDialogPeer.java:38)
> 	at sun.awt.X11.GtkFileDialogPeer$1.run(GtkFileDialogPeer.java:116)

Also no files are displayed just folders.

**Comment by X3msnake** [comment]
## PHOTON FILE VIEWER IS NO LONGER MANTAINED OR DEVELOPED!

Use [UVTools](https://github.com/sn4k3/UVtools/blob/master/README.md) by Master Photonster Tiago Conceição instead
